version: "3"

networks:
  app-tier:
    driver: bridge
    
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafka1:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka1
    ports:
      - "9092:9092" #<puerto del host>:<puerto del contenedor>
      - "9094:9094"
    volumes:
      - "kafka1_data:/bitnami" #"C:/Users/Drach/Documents/UDP/sistemasdistribuidos2/Tarea 2/Kafka/bitnami/kafka:/bitnami/kafka"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ENABLE_KRAFT=no
    networks:
      - app-tier
    depends_on:
      - zookeeper
  kafka2:
      image: docker.io/bitnami/kafka:3.4
      container_name: kafka2
      ports:
        - "9091:9091" #<puerto del host>:<puerto del contenedor>
        - "9095:9095"
      volumes:
        - "kafka2_data:/bitnami" #"C:/Users/Drach/Documents/UDP/sistemasdistribuidos2/Tarea 2/Kafka/bitnami/kafka:/bitnami/kafka"
      environment:
        - KAFKA_BROKER_ID=2
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:9093,EXTERNAL://:9095
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9091,CONTROLLER://kafka2:9093,EXTERNAL://localhost:9095
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_ENABLE_KRAFT=no
      networks:
        - app-tier
      depends_on:
        - zookeeper
  kafka3:
      image: docker.io/bitnami/kafka:3.4
      container_name: kafka3
      ports:
        - "9090:9090" #<puerto del host>:<puerto del contenedor>
        - "9096:9096"
      volumes:
        - "kafka3_data:/bitnami" #"C:/Users/Drach/Documents/UDP/sistemasdistribuidos2/Tarea 2/Kafka/bitnami/kafka:/bitnami/kafka"
      environment:
        - KAFKA_BROKER_ID=3
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9093,EXTERNAL://:9096
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9090,CONTROLLER://kafka3:9093,EXTERNAL://localhost:9096
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_ENABLE_KRAFT=no
      networks:
        - app-tier
      depends_on:
        - zookeeper
volumes:
  zookeeper_data:
    driver: local
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local